// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebartqmdqvjjvwywslcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViYXJ0cW1kcXZqanZ3eXdzbGNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4Mzc3MTcsImV4cCI6MjA2ODQxMzcxN30.xca8LlfoUV9iZoaWMkVqC8BEfjf4Fn6cyoJIRJZJGgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});